# Generated by Django 5.2.4 on 2025-08-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutiques', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('responsable', 'Responsable boutique'), ('caissier', 'Caissier')], max_length=20),
        ),
    ]
