# Generated by Django 5.2.4 on 2025-08-14 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutiques', '0002_alter_utilisateur_role'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stock',
            new_name='MouvementStock',
        ),
        migrations.AlterUniqueTogether(
            name='mouvementstock',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='client',
            name='adresse',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='contact',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='nom',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='StockCourant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=0)),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boutiques.boutique')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boutiques.produit')),
            ],
            options={
                'unique_together': {('boutique', 'produit')},
            },
        ),
    ]
