# Generated by Django 5.2.4 on 2025-08-24 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutiques', '0003_rename_stock_mouvementstock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventairedetail',
            name='stock_vendu',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='client',
            name='adresse',
            field=models.TextField(blank=True, default='xxxxxx', null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='contact',
            field=models.CharField(blank=True, default='xxxxxx', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='nom',
            field=models.CharField(blank=True, default='xxxxxx', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inventaire',
            name='description',
            field=models.TextField(blank=True, default='xxxxxx', null=True),
        ),
    ]
